org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# 你已用 box64 解决 aapt2。如果 Gradle 仍拉官方 x86_64 aapt2，用下面这行指向你的 ARM64/box64 包装版：
#android.aapt2FromMavenOverride=/home/Gold/android-sdk/aapt2-box64/aapt2

