location ^~ /api/music-source/ {
    proxy_pass http://127.0.0.1:4127;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 25s;
    proxy_connect_timeout 5s;
    client_max_body_size 1k;
    access_log off;
}

location ^~ /api/media/ {
    proxy_pass http://127.0.0.1:4127;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 25s;
    proxy_connect_timeout 5s;
}

location = /source/ {
    proxy_pass http://127.0.0.1:4127;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    access_log off;
}
